# Install the apt prerequisites
addons:
  apt:
    packages:
      # - python-pygments   # Syntax highlighting is already provided

# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - tar xvzf bin/hugo_0.31_Linux-64bit.tar.gz -C bin/
  - chmod +x bin/hugo
  - export PATH=$PATH:bin/
  - bin/build

# Deploy to GitHub pages
deploy:
  provider: pages
  repo: younjinjeong.github.io
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master