version: 2

jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: tar xvzf bin/hugo_0.31_Linux-64bit.tar.gz -C bin/
      - run: chmod +x bin/hugo
      - run: export PATH=$PATH:bin/
      - run: bin/hugo
      - run: ls -alt public/
      - run:
          name: Setup CF CLI
          command: |
            curl -v -L -o cf-cli_amd64.deb 'https://cli.run.pivotal.io/stable?release=debian64&source=github'
            sudo dpkg -i cf-cli_amd64.deb
            cf -v
            cf api ${CF_ENDPOINT}  # alternately target your private Cloud Foundry deployment
            cf auth "$CF_USER" "$CF_PASSWORD"
            cf target -o "$CF_ORG" -s "$CF_SPACE"
      - run:
          name: CF deploy
          command: |
            cf api ${CF_ENDPOINT}  # alternately target your private Cloud Foundry deployment
            cf auth "$CF_USER" "$CF_PASSWORD"
            cf target -o "$CF_ORG" -s "$CF_SPACE"
            cd public/
            cf push ${CF_APPNAME} -m 512M -b staticfile_buildpack