version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: tar xvzf bin/hugo_0.31_Linux-64bit.tar.gz -C bin/
      - run: chmod +x bin/hugo
      - run: export PATH=$PATH:bin/
      - run: bin/hugo
      - run: ls -alt public/



            


        